version: "3.3"
services:
  mongodb:
    image: mongo:3.5
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
  web:
    image: ciwei123321/yapi:20191115
    command: /bin/bash -c "[ ! -e /home/yapi/log/init.lock ] && npm run install-server && touch /home/yapi/log/init.lock; node server/app.js"
    links:
      - mongodb:mongodb
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./config.json
        target: /home/yapi/config.json
      - type: bind
        source: ./data/yapi
        target: /home/yapi/log
